// Firebase configuration for the web app (project echo-protocol-da7f7).
//
// First generated by the FlutterFire CLI, then set by hand when the app moved
// to this project. The app is web-only (it imports dart:html), so there are
// no options for other platforms. field/config.js must carry the same values.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError('The Echo Protocol is a web-only app.');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzJSiLCLsrqFVGYtEtFeEofs-7NFJ03c0',
    appId: '1:648716688016:web:fb69ad0ed2711995771615',
    messagingSenderId: '648716688016',
    projectId: 'echo-protocol-da7f7',
    authDomain: 'echo-protocol-da7f7.firebaseapp.com',
    storageBucket: 'echo-protocol-da7f7.firebasestorage.app',
  );
}
