// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRLlcwWtroIaujD9aYBNj0xaoYBrs24dQ',
    appId: '1:512607074756:web:79f4ed43a97ad1b9d94c91',
    messagingSenderId: '512607074756',
    projectId: 'treasure-hunt-38935',
    authDomain: 'treasure-hunt-38935.firebaseapp.com',
    storageBucket: 'treasure-hunt-38935.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXrrtFF0lujaXRWblbSrBfgy4C9N22oHo',
    appId: '1:512607074756:android:bd937ceefd1009fcd94c91',
    messagingSenderId: '512607074756',
    projectId: 'treasure-hunt-38935',
    storageBucket: 'treasure-hunt-38935.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz6FxPfT2JMrRa615rCx1QwV8yL-b-WKs',
    appId: '1:512607074756:ios:004955556f95f5fdd94c91',
    messagingSenderId: '512607074756',
    projectId: 'treasure-hunt-38935',
    storageBucket: 'treasure-hunt-38935.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz6FxPfT2JMrRa615rCx1QwV8yL-b-WKs',
    appId: '1:512607074756:ios:004955556f95f5fdd94c91',
    messagingSenderId: '512607074756',
    projectId: 'treasure-hunt-38935',
    storageBucket: 'treasure-hunt-38935.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRLlcwWtroIaujD9aYBNj0xaoYBrs24dQ',
    appId: '1:512607074756:web:eee804ab40b4efd7d94c91',
    messagingSenderId: '512607074756',
    projectId: 'treasure-hunt-38935',
    authDomain: 'treasure-hunt-38935.firebaseapp.com',
    storageBucket: 'treasure-hunt-38935.firebasestorage.app',
  );
}
